Recipe App
Mhamad-Raad/ruby-on-rails-capstone pull request #29
Opened 2023-02-10 16:37 UTC by Mhamad-Raad

## In this branch we have the following updates:
- Added Association between the classes.
- Added controllers for the needed views.
- Added views for the users.
- Added the needed routes.
- Added models for data manipulation.
- Added the needed logic.
- Added the needed logic.
- Fulfilled all the requirements for the project.

### Done 🎉💯🔥

2023-02-10 17:27 UTC, AnselemOdims requested changes
### Hi @team, 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] It might not have been included in the instructions but because we are advised to use TDD approach, I strongly suggest you write tests.
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-10 17:27 UTC, AnselemOdims commented on app/views/devise/sessions/new.html.erb
> +  </div>
- [ ] I am currently stuck on the login page as I have to confirm my email. However, I do not get any mail when I sign up. This has not enabled me test the features. Please kindly fix this.

![image](https://user-images.githubusercontent.com/43995830/218155765-a186c424-78a1-4f4b-a195-05deecd50bdf.png)

2023-02-10 17:27 UTC, AnselemOdims commented on README.md
> +**[BlogApp]** This project, created using Ruby on Rails, provides a platform for users to discover and save their favorite recipes. With an intuitive interface and a user-friendly design, users can e
- [ ] Please kindly change this from `Blog App` to match the title of the current project

2023-02-10 22:02 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 22:02 UTC, bobb-Rob commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
- [ ] You may need to remove this `:confirmable` so that one can log in easily for now. When I remove this confirmable, I was able to log in. I see that your app works as expected. Please fix the issues pointed out and your project will be approved.

2023-02-10 22:05 UTC, Mhamad-Raad commented on app/views/layouts/application.html.erb
>      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
Hi there, This is happening because you need to setup bootstrap on your rails, we can make a video for you if you want or comment it on your system even so some of the styles might be missing.

2023-02-10 22:06 UTC, Mhamad-Raad commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
This works fine for us, do you want us to make a video to show the project?

2023-02-10 22:09 UTC, shakerAbuDrais commented on app/views/layouts/application.html.erb
>      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
As my partner mentioned and I would like to add that we added two lines in the readme file that solves this issue, since the application.css is built only when bootstrap is activated "installed"

2023-02-10 22:33 UTC, Mhamad-Raad commented on app/views/layouts/application.html.erb
>      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
@bobb-Rob

2023-02-10 23:47 UTC, Camilovelag commented on app/views/layouts/application.html.erb
>      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
Done 😄

2023-02-10 23:47 UTC, bobb-Rob commented on app/views/layouts/application.html.erb
>      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
Hello @Mhamad-Raad

2023-02-10 23:47 UTC, Camilovelag commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
Done 😄

2023-02-10 23:47 UTC, Camilovelag commented on app/views/devise/sessions/new.html.erb
> +  </div>
Done 😄

2023-02-10 23:48 UTC, Camilovelag commented on README.md
> +**[BlogApp]** This project, created using Ruby on Rails, provides a platform for users to discover and save their favorite recipes. With an intuitive interface and a user-friendly design, users can e
Done 😄

2023-02-10 23:48 UTC, Camilovelag commented on README.md
> +## 🚀 Live Demo <a name="live-demo"></a>
Done 😄

2023-02-10 23:51 UTC, bobb-Rob commented on app/views/layouts/application.html.erb
>      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
What you need to do is carefully explain the steps any user will take to set up your project and running. This will enable the next reviewer to see your project as you see it. Now we can see and learn how a very detailed **_README_** file makes collaboration very easy with less time and effort.

2023-02-11 00:16 UTC, alexander16108 approved these changes
Hi Team 👋🏾 👍🏾 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media1.giphy.com/media/3NUJ4FwSp4MJG/giphy.gif"/>

## Highlights

✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 22:54 UTC, merged